### ISSUE TITLE
Failed to activate the quick-scroll package

### ISSUE THREAD

**Issue by Spidersouris** [refkotay/quick-scroll#4]
[Enter steps to reproduce:]

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [quick-scroll](https://github.com/refkotay/quick-scroll) package 2.1.3

### Stack Trace

Failed to activate the quick-scroll package

```
At Cannot read property 'removeEventListener' of undefined

TypeError: Cannot read property 'removeEventListener' of undefined
    at /packages/quick-scroll/quick-scroll.coffee:28:30
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/workspace.js:717:15)
    at Object.activate (/packages/quick-scroll/quick-scroll.coffee:26:25)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:58.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
file-icons 2.1.7 
flex-tool-bar 0.12.0 
french-menu 0.3.1 
intentions 1.1.2 
keyboard-sounds 0.2.0 
language-lua 0.9.11 
less-than-slash 0.16.0 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-luaparse 0.2.0 
linter-ui-default 1.6.1 
minimap 4.28.2 
pigments 0.39.1 
quick-scroll 2.1.3 
smart-tab-name 1.0.5 
tab-smart-sort 0.3.0 
tool-bar 1.1.0 
```

**Comment by SachinKodagoda** [comment]
Please fix it

**Comment by jolsen71** [comment]
It appears PR #5 is a an attempt to fix this issue--hopefully it'll get accepted and a new build released soon.

**Comment by didiergm** [comment]
FYI this also happens with atom 20

**Comment by stephyswe** [comment]
still problems :(

**Comment by Stibbons** [comment]
same issue here

**Comment by vitaliy-grusha** [comment]
What's wrong?

**Comment by Mikelle02** [comment]
Same issue here

**Comment by samej71** [comment]
@refkotay First, I'd like to thank you for everything you've done so far. Life has a way of keeping us busy and priorities change. Would you be willing to add one or more other people as collaborators of this package, so we can accept merge requests and create updated versions of this package while you're away? If so, please add me. Otherwise, I or someone will probably fork this project and call it  "quick-scroll2" or something, fix a couple bugs, and then publish it to Atom, but I'd much rather see your original package updated and not have two nearly identical packages in Atom cluttering things up and confusing people. Please consider adding some additional collaborators so we can help keep your original project up to date without taking any more of your time. Thanks!
